- name: Deploy a JS application in the document root of a web server 
  # Inventory should com in the template, if from REST, then a variable
  hosts: all
  # Apache dir and services require root to modify
  become: true
  vars:
    # Should come from an extra var
    # git_branch: 
    git_source_url: https://github.com/hgonzalerh/js-to-do.git
    documentroot: /var/www/html

  tasks:
    - name: latest Apache version installed
      ansible.builtin.yum:
        name: 
          - httpd
          - git
        state: latest

    - name: Apache enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started  

    - name: Deploy the webpage to documentroot
      ansible.builtin.git:
        repo: "{{ git_source_url }}"
        version: "{{ git_branch }}" 
        dest: "{{ documentroot }}"

    - name: Make sure the docroot is exposed and theres an index.html file or similar
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}/
