- name: Gather facts for all inventory
  hosts: all
  # redundant but explicit
  gather_facts: true
  tasks:
    - name: Show all facts we're insterested in, for debugging only
      ansible.builtin.debug:
        var: "{{ item }}"
        verbosity: 2
      loop:
        - ansible_distribution_version
        - ansible_kernel
        - ansible_processor
        - ansible_system_vendor
        - ansible_swaptotal_mb
        - ansible_machine
        - ansible_memtotal_mb
        - ansible_dns.nameservers
        - ansible_processor_count
        - ansible_all_ipv4_addresses

    - name: Create a custom fact that's the list of disks 
      ansible.builtin.set_fact:
        discos_fisicos: >-
          {{ 
            ansible_devices | dict2items | selectattr('value.host') | sort(attribute='key') | map(attribute='key') 
            | zip(
            ansible_devices | dict2items | selectattr('value.host') | sort(attribute='key') | map(attribute='value.size') 
                ) 
          }}
      when: ('indows' not in ansible_os_family)

- name: Render template
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Render file locally
      ansible.builtin.template:
        src: templates/report.csv.j2
        dest: report_hw.csv

- name: Copy report to the first server in the inventory
  hosts: all[0]
  gather_facts: false
  tasks:
    - name: Copy report (on Linux)
      ansible.builtin.copy:
        src: report_hw.csv
        dest: ./
      tags:
        - transfer
      when: ('indows' not in ansible_os_family)

    - name: Copy report (on Windows)
      ansible.builtin.win_copy:
        src: report_hw.csv
        dest: c:\
      tags:
        - transfer
      when: ('indows' in ansible_os_family)